---
title: "Indices and Management Type Admin"
output: pdf_document
author: "Alarice Chetty"
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(reshape2)
library(knitr)
library(GGally)
library(lme4)
library(geepack)
library(randomForest)
```

##admin
```{r data,include=FALSE, echo=FALSE}
data_RBS        = read_excel("indices/indices_ACSTC_1906_2607_combined.xlsx")  ##indices data
data_mes1       = read_excel("indices/indices_BACI_0308_1508_combined.xlsx")   ##indices data
data_mes2       = read_excel("indices/indices_BACI_1508_1409_combined.xlsx")   ##indices data 
data_RBS_morn   = read_excel("indices/indices_ACSTC_1906_2607_morning_combined.xlsx") ##indices data
data_mes1_morn  = read_excel("indices/indices_BACI_0308_1508_morning_combined.xlsx")  ##indices data
data_mes2_morn  = read_excel("indices/indices_BACI_1508_1409_morning_combined.xlsx")  ##indices data 

data       = rbind(data_RBS,data_mes1,data_mes2,data_RBS_morn,data_mes1_morn,data_mes2_morn)  ##combine data
site_RBS   = read.csv("RBS_Acoustic_metadata_table.csv")                ##site RBS data
site_mes   = read.csv("LLBN_MES_camera_grid.csv")                             ##site MES data
data$site_id = sub("_"," ",data$site_id)
data$station_id = sub("_"," ",data$station_id)

unique(data$site_id)
unique(data$station_id)

data = data[-which(data$site_id== "RBS 30"),]  # Remove point "RBS 30"
exc_dev = filter(site_RBS,longitude < 37.345)$station_name # filter for Lewa - RBS data
data = filter(data,!site_id %in% exc_dev)

site_RBS           = rename(site_RBS,c("station_name"="site_id"))|> select(site_id,treatment) ##retrieving treatment
site_RBS$treatment = tolower(site_RBS$treatment)                        ##lower case


site_mes            = rename(site_mes,c("stratum"="treatment"))|>rename(c("seq_id"="site_id"))|>select(site_id,treatment) ##retrieving treatment
site_mes$site_id = sub("","mes",site_mes$site_id)                       ##format
site_mes$treatment  = sub("extension","control",site_mes$treatment)    ##format
site_mes$treatment  = sub("exclosure","exclusion",site_mes$treatment)   ##format

site = rbind(site_RBS,site_mes)                                         ##combine site data
data = unique(data)
data  = merge(data,site,by="site_id")  ##merge treatment column to indices data
#data[,9:14] = scale(data[,9:14])
#write.csv(data, file="data_combined8.csv")
```

##admin
```{r structure, include=FALSE, echo=FALSE}
attach(data)
data$treatment = as.factor(data$treatment)        ##factor treatment
data$aci       = as.numeric(aci)                  ##indices from character to numeric
data$ad        = as.numeric(ad)
data$aei       = as.numeric(aei)
data$bi        = as.numeric(bi)
data$total_ent = as.numeric(total_ent)
data$ndsi      = as.numeric(ndsi)

indices=c("ACI","ADI","AEI","BIO","H","NDSI")

```

##filtering times
```{r times, include=FALSE, echo=FALSE}
##morning times 
data$time  = as.POSIXct(data$time)      ##put time data in correct form
start_morn = as.POSIXct("1899-12-31 07:30:00")   ##start time
end_morn   = as.POSIXct("1899-12-31 09:30:00")   ##end time
morn_data  = data[data$time >= start_morn & data$time <= end_morn, ] ##filter time 

##evening times 
start_even = as.POSIXct("1899-12-31 18:30:00")                       ##start time
end_even   = as.POSIXct("1899-12-31 20:55:00")                       ##end time
even_data  = data[data$time >= start_even & data$time <= end_even, ] ##filter time 

##peak times
peak_data  = rbind(morn_data,even_data)
#write.csv(peak_data, file = "data_peak8.csv")
#write.csv(morn_data, file = "data_morning8.csv")
#write.csv(even_data, file = "data_evening8.csv")
```
